### ISSUE TITLE
Discussion: creating multiple packages within the library

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#110]
This is not an issue per se but rather a discussion, and I wanted to write down some notes on this, maybe for use at a later time when the library has grown. I assume we won't need this right away, but I wanted to have the steps written down for when the time comes.

It is very common for Java and Kotlin libraries to break into distinct packages grouping functionality, for the same reasons Rust modules are used in BDK. I wasn't sure if we'd have the ability to do this because the package name is defined in the `uniffi.toml` file and not in the udl file (so at first glance, not matter how many udl files you create they all have the same package name), but after opening an issue on the uniffi-rs repo they told me about the ability to provide a custom `uniffi.toml` file for each call to the `uniffi_bindgen`. So if we define more than one udl file and generate the bindings using different config files, it's possible to create any number of packages.

Example:
```sh
uniffi-bindgen generate src/first.udl --no-format --config-path ./firstuniffi.toml --out-dir ./ --language kotlin
uniffi-bindgen generate src/second.udl --no-format --config-path ./seconduniffi.toml --out-dir ./ --language kotlin
```

And each uniffi.toml file can simply declare its own package name:
```toml
# firstuniffi.toml
[bindings.kotlin]
package_name = "org.bitcoindevkit.wallet"
cdylib_name = "bdkffi"
```

```toml
# seconduniffi.toml
[bindings.kotlin]
package_name = "org.bitcoindevkit.keys"
cdylib_name = "bdkffi"
```
