### ISSUE TITLE
Remove Cargo authors line

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-ffi#407]
In a future PR I want to remove this line and replace it with:
```toml
homepage = "https://bitcoindevkit.org"
repository = "https://github.com/bitcoindevkit/bdk"
```

_Originally posted by @notmandatory in https://github.com/bitcoindevkit/bdk-ffi/pull/402#discussion_r1368925254_
